### ISSUE TITLE
Outdated WordPress version

### ISSUE THREAD

**Issue by emrikol** [iolevel/peachpie-wordpress#1]
It looks like the version of WordPress here is [4.7-beta3-39214](https://github.com/iolevel/peachpie-wordpress/blob/master/website/wp-includes/version.php#L7) so it's likely susceptible to the [WordPress REST API content injection vulnerability](https://blog.sucuri.net/2017/02/content-injection-vulnerability-wordpress-rest-api.html).

**Comment by jakubmisek** [comment]
thanks we'll be definitely updating wp in this repo continuously. For now, we have to close Issues section as it was for sure already reported to wp and we tend to not make modifications to wp sources here.
